// Helpers to export a review as Markdown and copy text to the clipboard.

export function reviewToMarkdown({ filename, review }) {
  const lines = [];
  lines.push(`# Code Review${filename ? ` — ${filename}` : ''}`);
  lines.push('');
  lines.push(`**Language:** ${review.language}  `);
  if (review.score != null) lines.push(`**Score:** ${review.score} / 100  `);
  lines.push('');
  lines.push(`## Summary`);
  lines.push(review.summary || '_No summary._');
  lines.push('');

  if (review.strengths?.length) {
    lines.push('## Strengths');
    review.strengths.forEach((s) => lines.push(`- ${s}`));
    lines.push('');
  }

  if (review.issues?.length) {
    lines.push(`## Issues (${review.issues.length})`);
    review.issues.forEach((i, n) => {
      lines.push('');
      lines.push(
        `### ${n + 1}. ${i.title}  \`${i.severity}\` · \`${i.category}\`${
          i.line != null ? ` · line ${i.line}` : ''
        }`
      );
      if (i.description) lines.push(i.description);
      if (i.suggestion) {
        lines.push('');
        lines.push('**Suggested fix:**');
        lines.push('```');
        lines.push(i.suggestion);
        lines.push('```');
      }
    });
  } else {
    lines.push('## Issues');
    lines.push('No issues found. ✅');
  }

  lines.push('');
  lines.push('---');
  lines.push('_Generated by the AI Code Review Assistant._');
  return lines.join('\n');
}

export function downloadMarkdown(result) {
  // Handle both single and multi-file (GitHub) results.
  let md;
  let name = 'code-review';
  if (Array.isArray(result.reviews)) {
    md = result.reviews
      .filter((r) => r.review)
      .map((r) => reviewToMarkdown(r))
      .join('\n\n---\n\n');
    name = `${result.source?.repo || 'github'}-review`;
  } else {
    md = reviewToMarkdown(result);
    name = (result.filename || 'code-review').replace(/[^\w.-]/g, '_');
  }

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${name}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
